#测试集群
server=(172.16.0.4 172.16.0.5)
#分布式集群的SEED_NODES参数
seeds="172.16.0.4:9003:40010:55560,172.16.0.5:9003:40010:55560"
#打包的文件名
snapshotName="cluster-0.11.0-SNAPSHOT"
#本地的集群maven打包路径
snapshotPath="/Users/txy/Study/incubator-iotdb/cluster/target/${snapshotName}"
#测试集群的执行路径
serverPath="~/txy_test/${snapshotName}"
#从测试集群拉取得到的执行日志本地路径
localLogDir="result"
#服务器新建的文件夹名称
serverDir="txy_test"
#服务器用户
user="root"
#更改iotdb-cluster.properties中的属性，用|隔开，格式为key=value，即key为参数名称，value为值的方式替代对应文件中的参数
clusterConfig="seed_nodes=${seeds}|is_enable_raft_log_persistence=false|default_replica_num=2|is_use_async_server=false|enable_auto_create_schema=false|is_use_async_applier=true"
#更改iotdb-engine.properties中的属性，用|隔开，格式为key=value，即key为参数名称，value为值的方式替代对应文件中的参数
engineConfig=""
#是否后台启动集群
execute=true
#是否从本地推包
push=true